### ISSUE TITLE
core_privacy\local\request\moodle_content_writer::export_data(): Argument #2 ($data) must be of type stdClass,

### ISSUE THREAD

**Issue by lassnj** [dualcube/moodle-tool_inactive_user_cleanup#28]
Hi,
I got an automated E-Mail from the Moodle System (4.4) informing me, that there is a problem with the interactive user cleanup tool (latest version):

```
Exception occurred while calling tool_inactive_user_cleanup\privacy\provider::export_user_data.
This means that plugin tool_inactive_user_cleanup did not complete the processing of data. The following exception information may be passed on to the plugin developer:
core_privacy\local\request\moodle_content_writer::export_data(): Argument #2 ($data) must be of type stdClass, array given, called in /data/web/www/vhosts/www.mysite.at/admin/tool/inactive_user_cleanup/classes/privacy/provider.php on line 162
```
```
#0 /data/web/www/vhosts/www.mysite.at/admin/tool/inactive_user_cleanup/classes/privacy/provider.php(162): core_privacy\local\request\moodle_content_writer->export_data(Array, Array)
#1 /data/web/www/vhosts/www.mysite.at/lib/moodlelib.php(7829): tool_inactive_user_cleanup\privacy\provider::export_user_data(Object(core_privacy\local\request\approved_contextlist))
#2 /data/web/www/vhosts/www.mysite.at/privacy/classes/manager.php(578): component_class_callback('tool_inactive_u...', 'export_user_dat...', Array)
#3 /data/web/www/vhosts/www.mysite.at/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('tool_inactive_u...', 'core_privacy\\lo...', 'export_user_dat...', Array)
#4 /data/web/www/vhosts/www.mysite.at/privacy/classes/manager.php(339): core_privacy\manager->handled_component_class_callback('tool_inactive_u...', 'core_privacy\\lo...', 'export_user_dat...', Array)
#5 /data/web/www/vhosts/www.mysite.at/admin/tool/dataprivacy/classes/task/process_data_request_task.php(122): core_privacy\manager->export_user_data(Object(core_privacy\local\request\contextlist_collection))
#6 /data/web/www/vhosts/www.mysite.at/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#7 /data/web/www/vhosts/www.mysite.at/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#8 /data/web/www/vhosts/www.mysite.at/admin/cli/adhoc_task.php(174): core\cron::run_adhoc_tasks(1723795622, 59, true, 1723795622, NULL, NULL)
#9 {main}
```
Could you please fix this? Thanks a lot!

**Comment by moumitahalder** [comment]
Hi @lassnj, We're sorry to hear you've encountered this issue. Since we're unable to replicate it on our end, could you please provide details on how to recreate it? This will help us assist you more effectively.

**Comment by lassnj** [comment]
hi moumitahalder,
thanks for getting back to me. I did receive this email only once to notify me that there is a problem with the plugin in combination with the data privacy tool. I deactivated the cron job on our production system as i am unable to set the plugin settings to 0. I do, save and it seems to work, but when I change to another admin page and come back, the default value is still present. It also does not save my email configuration. Not sure if this is related though.
However, the data privacy tool notified me of another problem:

```
Call to undefined method core\context\module::get_user()

#0 /data/web/www/vhosts/www.mysite.at/lib/moodlelib.php(7829): tool_inactive_user_cleanup\privacy\provider::delete_data_for_user(Object(core_privacy\local\request\approved_contextlist))
#1 /data/web/www/vhosts/www.mysite.at/privacy/classes/manager.php(578): component_class_callback('tool_inactive_u...', 'delete_data_for...', Array)
#2 /data/web/www/vhosts/www.mysite.at/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('tool_inactive_u...', 'core_privacy\\lo...', 'delete_data_for...', Array)
#3 /data/web/www/vhosts/www.mysite.at/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback('tool_inactive_u...', 'core_privacy\\lo...', 'delete_data_for...', Array)
#4 /data/web/www/vhosts/www.mysite.at/admin/tool/dataprivacy/classes/task/process_data_request_task.php(151): core_privacy\manager->delete_data_for_user(Object(core_privacy\local\request\contextlist_collection))
#5 /data/web/www/vhosts/www.mysite.at/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#6 /data/web/www/vhosts/www.mysite.at/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#7 /data/web/www/vhosts/www.mysite.at/admin/cli/adhoc_task.php(174): core\cron::run_adhoc_tasks(id, 59, true, 1724255821, NULL, NULL)
#8 {main}
```

Thanks a lot
Regards Julia

**Comment by moumitahalder** [comment]
Julia, thank for getting back to us. 

Can you please share a video with us so we can try to recreate the same on our end.
