### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moodle-tool_inactive_user_cleanup#29]
Using Moodle 4.3.3 and the latest version of the plugin (2.7.4) I see the following error message:

Exception occurred while calling tool_inactive_user_cleanup\privacy\provider::get_contexts_for_userid.
This means that plugin tool_inactive_user_cleanup did not complete the processing of data. The following exception information may be passed on to the plugin developer:

ERROR: Incorrect number of query parameters. Expected 3, got 2.

#0 /home/xxx/public_html/lib/dml/mysqli_native_moodle_database.php(1331): moodle_database->fix_sql_params('\n ...', Array)
#1 /home/xxx/public_html/privacy/classes/local/request/contextlist.php(71): mysqli_native_moodle_database->get_recordset_sql('\n ...', Array)
#2 /home/xxx/public_html/admin/tool/inactive_user_cleanup/classes/privacy/provider.php(148): core_privacy\local\request\contextlist->add_from_sql('SELECT c.id\n ...', Array)
#3 /home/xxx/public_html/lib/moodlelib.php(8292): tool_inactive_user_cleanup\privacy\provider::get_contexts_for_userid(41872)
#4 /home/xxx/public_html/privacy/classes/manager.php(578): component_class_callback('tool_inactive_u...', 'get_contexts_fo...', Array)
#5 /home/xxx/public_html/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('tool_inactive_u...', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#6 /home/xxx/public_html/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('tool_inactive_u...', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /home/xxx/public_html/admin/tool/dataprivacy/classes/task/process_data_request_task.php(93): core_privacy\manager->get_contexts_for_userid(41872)
#8 /home/xxx/public_html/lib/classes/cron.php(508): tool_dataprivacy\task\process_data_request_task->execute()
#9 /home/xxx/public_html/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#10 /home/xxx/public_html/lib/classes/cron.php(128): core\cron::run_adhoc_tasks(1726563604, 0, true, 1726563602)
#11 /home/xxx/public_html/admin/cron.php(80): core\cron::run_main_process(0)
#12 {main}

**Comment by Nakun1** [comment]
Hello, same here

Moodle 4.1.4

Plugin version : 2.7.4

**Comment by moumitahalder** [comment]
Hi @Nakun1, we have fixed this on our end. 
Kindly download the plugin from here- https://github.com/dualcube/moodle-tool_inactive_user_cleanup

So, after downloading the plugin from here, follow these steps :
– Delete the installed plugin and 
– Unzip the GitHub plugin
– Rename the folder as “moodle-tool_inactive_user_cleanup” and remove the master tag. Now, zip this folder again.
– Install this plugin on your site.
Please do keep us posted.

**Comment by Nakun1** [comment]
Hi @moumitahalder , 
Thank you for sharing this fix; everything seems to be working now! :)

**Comment by moumitahalder** [comment]
Hi @Nakun1, we have added the fix in our GitHub repo.
Kindly download the plugin from here and check.

Please do keep us posted, so we can also release the update.

**Comment by Nakun1** [comment]
Hi,

If I update the plugin, is there a risk of users being notified multiple times?

For the past two nights, I haven't had any errors, and the cleanup is working well, so I'm hesitant to update.

**Comment by moumitahalder** [comment]
Hi @Nakun1, Not to worry.

Updating the plugin will not notify multiple users.
